# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Kick-Starter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Kick-Starter

  pod 'Firebase/Auth'
  pod 'Firebase/Core'

  # pod 'KickStarterFramework', :git => 'https://github.com/AbdullahNanaDVT/KickStarterFramework.git' 
  pod 'KickStarterFramework', :path => '/Users/anana/Desktop/KickStarterFramework/KickStarterFramework' 

  target 'Kick-StarterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Kick-StarterUITests' do
    # Pods for testing
  end

end
